title: <strong>K<blackinvt><em>A</em>I</blackinvt>ST  <pink>BR</pink><pinkinvt><em>A</em>I</pinkinvt><pink>N</pink>  <blue><em>Re</em>P</blue><blueinvt><em>A</em>I</blueinvt><blue>R</blue>  &  ORGANOID  INTEL</strong>
subtitle: by Minee Choi
team: <strong><pink>B</pink><blue><em>Re</em>P</blue><blueinvt><em>A</em>I</blueinvt><blue>R</blue></strong>
description: KAIST BRAIN RePAIR & ORGANOID INTELLIGENCE
logo-text: true
header: images/background.jpg
footer: images/footer.jpg
links:
  email: minee.choi@kaist.ac.kr
  orcid: 0000-0001-9414-8214
  google-scholar: _N6YhZUAAAAJ
  research-gate: Minee-Liane-Choi-2
  github: Minee-Liane-Choi
  twitter: MineeChoi
  youtube: 
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: programmes
    values:
      layout: programme
collections:
  members:
    output: true
  posts:
    output: true
  programmes:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: 
github: 
twitter: 
instagram: 
youtube: 
