title: <strong><red>BR</red><redinvt><em>A</em>I</redinvt><red>N</red>  <blue><em>Re</em>P</blue><blueinvt><em>A</em>I</blueinvt><blue>R</blue></strong>
subtitle: Minee Choi's Lab
team: <strong><red>B</red><blue><em>Re</em>P</blue><blueinvt><em>A</em>I</blueinvt><blue>R</blue></strong>
description: Brain Repair Lab of KAIST
logo-text: true
header: images/background.jpg
footer: images/footer.jpg
links:
  email: minee.choi@kaist.ac.kr
  orcid: 0000-0001-9414-8214
  google-scholar: _N6YhZUAAAAJ
  github: Minee-Liane-Choi
  twitter: MineeChoi
  youtube: 
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: programmes
    values:
      layout: member
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: 
github: 
twitter: 
instagram: 
youtube: 
