title: BR<mark><strong>AI</strong></mark>N &nbsp; ReP<mark><strong>AI</strong></mark>R &nbsp; LAB
subtitle: Minee Choi's Lab
description: #Parkinson’s #Alzheimer’s #Dimentia #AI-based drug discovery #Mitochondria #Protein aggregation #Cell death
logo-text: true
header: images/background.jpg
footer: images/neuron.jpg
links:
  email: minee.choi@kaist.ac.kr
  orcid: 0000-0001-9414-8214
  google-scholar: _EN6YhZUAAAAJ
  github: Minee-Liane-Choi
  twitter: MineeChoi
  youtube: 
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: 
github: 
twitter: 
instagram: 
youtube: 
