title: Brain Repair Laboratory
subtitle: Minee Choi's Lab
description: An engaging 1-3 sentence description of your lab.
logo-text: true
header: images/background.jpg
footer: images/background.jpg
links:
  email: minee.choi@kaist.ac.kr
  orcid: 0000-0001-9414-8214
  google-scholar: ETJoidYAAAAJ
  github: https://github.com/Minee-Liane-Choi
  twitter: https://twitter.com/MineeChoi
  youtube: 
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: Minee-Liane Choi
github: Minee-Liane Choi
twitter: Minee-Liane Choi
instagram: Minee-Liane Choi
youtube: Minee-Liane Choi
