title: <strong><redinvt>BR</redinvt><red><em>A</em>I</red><redinvt>N</redinvt>  <blueinvt>ReP</blueinvt><blue><em>A</em>I</blue><blueinvt>R</blueinvt> Lab</strong>
subtitle: Minee Choi's Lab
team: <strong><redinvt>B</redinvt>ReP<blue><em>A</em>I</blue>R</strong>
description: #Parkinson’s #Alzheimer’s #Dimentia #AI-based drug discovery #Mitochondria #Protein aggregation #Cell death
logo-text: true
header: images/background.jpg
footer: images/footer.jpg
links:
  email: minee.choi@kaist.ac.kr
  orcid: 0000-0001-9414-8214
  google-scholar: _EN6YhZUAAAAJ
  github: Minee-Liane-Choi
  twitter: MineeChoi
  youtube: 
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: 
github: 
twitter: 
instagram: 
youtube: 
