
- id: doi:10.1038/s41531-022-00423-7
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41531-022-00423-7/MediaObjects/41531_2022_423_Fig8_HTML.png?as=webp
  tags:
    - PD
    - iPSC
    
- id: doi:10.1038/s41593-022-01140-3
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41593-022-01140-3/MediaObjects/41593_2022_1140_Fig8_HTML.png?as=webp
  tags:
    - PD
    - iPSC
    - Mitocondria

- id: doi:10.1002/mds.29122
  image: https://movementdisorders.onlinelibrary.wiley.com/cms/asset/694968c7-fed7-49a1-bf22-c9d5c347547a/mds.v37.8.cover.jpg
  tags:
    - PD
    - iPSC
    
- id: doi:10.1038/s41418-020-0542-z
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41418-020-0542-z/MediaObjects/41418_2020_542_Fig6_HTML.png?as=webp
  tags:
    - PD
    - iPSC
    
- id: doi:10.1038/s42003-020-0792-9
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs42003-020-0792-9/MediaObjects/42003_2020_792_Fig4_HTML.png?as=webp
  tags:
    - PD
    - iPSC
    
- id: doi:10.1007/s00401-018-1907-y
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs00401-018-1907-y/MediaObjects/401_2018_1907_Fig1_HTML.png?as=webp
  tags:
    - PD
    - iPSC
    
- id: doi:10.1002/cbic.201800209
  image: https://chemistry-europe.onlinelibrary.wiley.com/cms/asset/5397eb37-34f9-43e6-86f2-0e8509247448/cbic.v19.19.cover.jpg
  tags:
    - PD
    - iPSC
    
- id: doi:10.1111/febs.14587
  image: https://febs.onlinelibrary.wiley.com/cms/asset/678ff62a-d26a-4566-ba0c-99d67daa3f07/febs.2018.285.issue-19.cover.jpg
  tags:
    - PD
    - iPSC
    
- id: doi:10.1038/s41467-018-04422-2
  image: https://www.repository.cam.ac.uk/bitstream/handle/1810/269918/srep33928.pdf.jpg?sequence=5&isAllowed=y
  tags:
    - PD
    - iPSC
    
- id: doi:10.17863/CAM.16793
  image: https://www.repository.cam.ac.uk/bitstream/handle/1810/269918/srep33928.pdf.jpg?sequence=5&isAllowed=y
  tags:
    - PD
    - iPSC
    
- id: doi:10.1186/s12915-017-0390-6
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs12915-017-0390-6/MediaObjects/12915_2017_390_Fig2_HTML.gif?as=webp
  tags:
    - PD
    - iPSC

- id: doi:10.1016/j.celrep.2017.05.024
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2211124716X0023X-cov200h.gif
  tags:
    - PD
    - iPSC
    
- id: doi:10.1038/srep33928
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fsrep33928/MediaObjects/41598_2016_Article_BFsrep33928_Fig6_HTML.jpg?as=webp
  tags:
    - PD
    - iPSC

- id: doi:10.1016/j.bpj.2015.11.2522
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0006349515X00051-cov200h.gif
  tags:
    - PD
    - iPSC

- id: doi:10.1073/pnas.1524128113
  image: https://www.pnas.org/cms/10.1073/pnas.1524128113/asset/c42cffeb-76fd-4033-b335-2f33759ef93a/assets/graphic/pnas.1524128113fig01.jpeg
  tags:
    - PD
    - iPSC

- id: doi:10.1002/hipo.22541
  image: https://onlinelibrary.wiley.com/cms/asset/cfbcf59f-2b3e-4875-a431-b305a0113459/hipo.v26.4.cover.jpg
  tags:
    - PD
    - iPSC

- id: doi:10.1016/j.neulet.2015.01.084
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0304394015X00073-cov200h.gif
  tags:
    - PD
    - iPSC

- id: doi:10.1016/j.nbd.2014.02.004
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0969996114X00033-cov200h.gif
  tags:
    - PD
    - iPSC

- id: doi:10.1126/science.1173215
  image: https://www.science.org/cms/asset/8eb1c9f8-04ac-4c70-ad0c-c655561acdf6/science.2009.325.issue-5937.largecover.jpg
  tags:
    - PD
    - iPSC

- id: doi:10.1016/j.cellsig.2007.12.009
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0898656807X01785-cov200h.gif
  tags:
    - PD
    - iPSC
