
- id: doi:10.1038/s41531-022-00423-7
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41531-022-00423-7/MediaObjects/41531_2022_423_Fig8_HTML.png?as=webp
  tags:
    - PD
    - iPSC

- id: doi:10.1038/s41593-022-01140-3
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41593-022-01140-3/MediaObjects/41593_2022_1140_Fig8_HTML.png?as=webp
  tags:
    - PD
    - iPSC
    - iPSC

- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review
