
- id: doi:10.1038/s41531-022-00423-7
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41531-022-00423-7/MediaObjects/41531_2022_423_Fig8_HTML.png?as=webp
  tags:
    - PD
    - iPSC
    
- id: doi:10.1038/s41593-022-01140-3
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41593-022-01140-3/MediaObjects/41593_2022_1140_Fig8_HTML.png?as=webp
  tags:
    - PD
    - iPSC
    - Mitocondria

- id: doi:10.1002/mds.29122
  image: https://movementdisorders.onlinelibrary.wiley.com/cms/asset/72fcf5a6-de87-4b21-8dad-0157d76ad85b/mds29122-fig-0001-m.png
  tags:
    - PD
    - iPSC
    
- id: doi:10.1038/s41418-020-0542-z
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41418-020-0542-z/MediaObjects/41418_2020_542_Fig6_HTML.png?as=webp
  tags:
    - PD
    - iPSC
    
- id: doi:10.1038/s42003-020-0792-9
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs42003-020-0792-9/MediaObjects/42003_2020_792_Fig4_HTML.png?as=webp
  tags:
    - PD
    - iPSC
    
- id: doi:10.1007/s00401-018-1907-y
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs00401-018-1907-y/MediaObjects/401_2018_1907_Fig1_HTML.png?as=webp
  tags:
    - PD
    - iPSC
    
- id: doi:10.1002/cbic.201800209
  image: https://chemistry-europe.onlinelibrary.wiley.com/cms/asset/ff2f9c5e-a26d-45c2-9492-fedfabdfdc36/cbic201800209-toc-0001-m.png
  tags:
    - PD
    - iPSC
    
- id: doi:10.1111/febs.14587
  image: https://febs.onlinelibrary.wiley.com/cms/asset/c62eba3f-7b2f-4bfe-baf3-b8c3e29cf29c/febs14587-fig-0001-m.png
  tags:
    - PD
    - iPSC
    
- id: doi:10.1038/s41467-018-04422-2
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-018-04422-2/MediaObjects/41467_2018_4422_Fig3_HTML.jpg?as=webp
  tags:
    - PD
    - iPSC
    
- id: doi:10.1186/s12915-017-0390-6
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs12915-017-0390-6/MediaObjects/12915_2017_390_Fig2_HTML.gif?as=webp
  tags:
    - PD
    - iPSC

- id: doi:10.1016/j.celrep.2017.05.024
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2211124717306496-fx1.jpg
  tags:
    - PD
    - iPSC
    
- id: doi:10.1038/srep33928
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fsrep33928/MediaObjects/41598_2016_Article_BFsrep33928_Fig6_HTML.jpg?as=webp
  tags:
    - PD
    - iPSC

- id: doi: 10.1016/j.bpj.2015.11.2522
  image: 
  tags:
    - PD
    - iPSC

- id: doi: 10.1073/pnas.1524128113
  image: https://www.pnas.org/cms/10.1073/pnas.1524128113/asset/c42cffeb-76fd-4033-b335-2f33759ef93a/assets/graphic/pnas.1524128113fig01.jpeg
  tags:
    - PD
    - iPSC

- id: doi: 10.1002/hipo.22541
  image: https://onlinelibrary.wiley.com/cms/asset/e0fb40d3-f8ac-4574-a15b-553c2091b563/hipo22541-fig-0002-m.png
  tags:
    - PD
    - iPSC

- id: doi: 10.1016/j.neulet.2015.01.084
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0304394015001196-gr2.jpg
  tags:
    - PD
    - iPSC

- id: doi: 10.1016/j.nbd.2014.02.004
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0969996114000394-gr1.jpg
  tags:
    - PD
    - iPSC

- id: doi: 10.1126/science.1173215
  image: https://www.science.org/cms/asset/8eb1c9f8-04ac-4c70-ad0c-c655561acdf6/science.2009.325.issue-5937.largecover.jpg
  tags:
    - PD
    - iPSC

- id: doi: 10.1016/j.cellsig.2007.12.009
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0898656807003798-gr7.jpg
  tags:
    - PD
    - iPSC
