- id: doi:10.1126/sciadv.adp8504
  image: https://www.science.org/cms/asset/73ebd9e6-81df-452f-9ab8-19f63bc44fc2/sciadv.2025.11.issue-16.largecover.jpg
  tags:
    - Parkinson's
    - hiPSC
    - Alpha-Synuclein
    - Protein aggregation
    - 1st Author

- id: doi:10.1101/2024.02.26.582055
  image: ../images/archive/0000-00-Science2009-cover.jpg
  tags:
    - Parkinson's
    - hiPSC
    - 1st Author
    
- id: doi:10.1101/2024.05.30.596437
  image: ../images/archive/0000-00-BioRxiv-cover.jpg
  tags:
    - Parkinson's
    - hiPSC

- id: doi:10.1101/2024.02.28.582460
  image: ../images/archive/0000-00-BioRxiv-cover.jpg
  tags:
    - Parkinson's
    - hiPSC

- id: doi:10.1038/s42256-023-00702-9
  image: https://media.springernature.com/w440/springer-static/cover-hires/journal/42256/5/8
  tags:
    - AI
    - Parkinson's
    - hiPSC
    - Corresponding author
    
- id: doi:10.1038/s41531-022-00423-7
  image: https://media.springernature.com/full/nature-cms/uploads/product/npjparkd/header-c65b5209b1a015d1bb160caf59641545.svg
  tags:
    - Protein aggregation
    - Parkinson's
    - hiPSC
    
- id: doi:10.1038/s41593-022-01140-3
  image: https://media.springernature.com/w200/springer-static/cover-hires/journal/41593/25/9
  tags:
    - Synucleinopathy
    - Protein aggregation
    - Parkinson's
    - Mitochondria
    - hiPSC
    - 1st Author

- id: doi:10.1002/mds.29122
  image: https://movementdisorders.onlinelibrary.wiley.com/cms/asset/694968c7-fed7-49a1-bf22-c9d5c347547a/mds.v37.8.cover.jpg
  tags:
    - Parkinson's
    
- id: doi:10.1038/s41418-020-0542-z
  image: https://media.springernature.com/w200/springer-static/cover-hires/journal/41418/27/7
  tags:
    - Synucleinopathy
    - Protein aggregation
    - Parkinson's 
    - Ferroptosis
    - 1st Author
    
- id: doi:10.1038/s42003-020-0792-9
  image: https://th.bing.com/th?id=OSK.f00bfb73a4a4b227ae33f35139ff6094&w=92&h=124&c=7&o=6&dpr=1.3&pid=SANGAM
  tags:
    - Inflammation
    - Alzheimer's
    - Protein aggregation
    - hiPSC
    
- id: doi:10.1016/j.bpj.2019.11.1289
  image: https://www.cell.com/cms/asset/08f4efb2-16ac-4b43-820a-ba45eb40b10f/cov200h.gif
  tags:
    - Alpha-Synuclein
    - Mitochondria
    - 1st Author
    
- id: doi:10.1007/s00401-018-1907-y
  image: https://media.springernature.com/w138/springer-static/cover/journal/401/137/1.jpg
  tags:
    - Parkinson's
    - Alpha-Synuclein
    - 1st Author
    
- id: doi:10.1002/cbic.201800209
  image: https://chemistry-europe.onlinelibrary.wiley.com/cms/asset/5397eb37-34f9-43e6-86f2-0e8509247448/cbic.v19.19.cover.jpg
  tags:
    - Protein aggregation
    - hiPSC
    
- id: doi:10.1111/febs.14587
  image: https://febs.onlinelibrary.wiley.com/cms/asset/678ff62a-d26a-4566-ba0c-99d67daa3f07/febs.2018.285.issue-19.cover.jpg
  tags:
    - Parkinson's
    - Alzheimer's
    - hiPSC
    - 1st Author
    
- id: doi:10.1038/s41467-018-04422-2
  image: https://th.bing.com/th?id=OSK.63c1f1e26188742d851a457bf4c6e09a&w=92&h=124&c=7&o=6&dpr=1.3&pid=SANGAM
  tags:
    - Parkinson's
    - Alpha-Synuclein
    - hiPSC
   
- id: doi:10.1016/j.freeradbiomed.2018.04.137
  image: https://ars.els-cdn.com/content/image/S08915849.gif
  tags:
    - Alpha-Synuclein
    - Ferroptosis
    
- id: doi:10.1016/j.freeradbiomed.2018.04.532
  image: https://ars.els-cdn.com/content/image/S08915849.gif
  tags:
    - Parkinson's
    - Cell death
    - iPSC
    - 1st Author
    
- id: doi:10.1186/s12915-017-0390-6
  image: https://th.bing.com/th?id=OSK.edfab221ed9e56106aadb6b386152e27&w=92&h=124&c=7&o=6&dpr=1.3&pid=SANGAM
  tags:
    - Alpha-Synuclein

- id: doi:10.1016/j.celrep.2017.05.024
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2211124716X0023X-cov200h.gif
  tags:
    - Parkinson's
    
- id: doi:10.1016/j.bpj.2016.11.2351
  image: https://www.cell.com/cms/asset/780de9ac-5681-4006-8c8b-d1792a98befe/cov200h.gif
  tags:
    - Parkinson's
    - Mitochondria
    - hiPSC
    
- id: doi:10.1038/srep33928
  image: https://www.openacessjournal.com/assets/membership/2020041548Scien.jpg
  tags:
    - Parkinson's
    - Alpha-Synuclein
    
- id: doi:10.1073/pnas.1524128113
  image: https://www.pnas.org/cms/asset/7a19cdf3-0b97-472a-b6e7-621e52e95bc8/pnas.2016.113.issue-7.largecover.png
  tags:
    - Parkinson's
    - Alpha-Synuclein

- id: doi:10.1016/j.bpj.2015.11.2522
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0006349515X00051-cov200h.gif
  tags:
    - Parkinson's
    - Alpha-Synuclein
    - Mitochondria
    - 1st Author

- id: doi:10.1002/hipo.22541
  image: https://onlinelibrary.wiley.com/cms/asset/cfbcf59f-2b3e-4875-a431-b305a0113459/hipo.v26.4.cover.jpg
  tags:
    - Hippocampus
    - 1st Author

- id: doi:10.1016/j.neulet.2015.01.084
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0304394015X00073-cov200h.gif
  tags:
    - Fabry disease
    - 1st Author

- id: doi:10.1016/j.nbd.2014.02.004
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0969996114X00033-cov200h.gif
  tags:
    - Neurogenesis
    - Huntington's
    - 1st Author

- id: doi:10.1126/science.1173215
  image: ../images/archive/0000-00-Science2009-cover.jpg
  tags:
    - Neurogenesis
    - Learning Memory

- id: doi:10.1016/j.cellsig.2007.12.009
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0898656807X01785-cov200h.gif
  tags:
    - Hippocampus
